=== Beira-BF/genia-event/original-data/GENIAtypes/GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term&event annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: 9 January 2008                    -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Other
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID			#REQUIRED
>

<!ELEMENT frag		(#PCDATA | term)*>
<!ATTLIST frag
		id  ID		#REQUIRED
>
<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, theme*, site*, product*, cause*, clue, comment?)>
<!ATTLIST event
		id		ID				#REQUIRED
		assertion	(exist|non-exist)		"exist"
		uncertainty 	(certain|probable|doubtful)	"certain"
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | corefTheme | corefSite | corefProduct | corefCause | clueExperiment)*>

<!ELEMENT clueType		(#PCDATA)>
<!ELEMENT linkTheme		(#PCDATA)>
<!ELEMENT linkCause		(#PCDATA)>
<!ELEMENT clueTime		(#PCDATA)>
<!ELEMENT clueLoc		(#PCDATA)>
<!ELEMENT clueExperiment	(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA)>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA)>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

=== Beira-BF/genia-event/original-data/GENIAcorpus_event/9047239.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="07/02/22" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9047239" creator="Yumiko Katsu">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9047239</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">A <term sem="DNA_domain_or_region" id="A101"><term sem="DNA_domain_or_region" id="T1" lex="T_cell-specific_enhancer">T cell-specific enhancer</term> in the <term sem="DNA_domain_or_region" id="T2" lex="interleukin-3_locus">interleukin-3 locus</term></term> is activated cooperatively by <cons sem="(AND DNA_domain_or_region DNA_domain_or_region)" id="T3" lex="(AND Oct_element NFAT_element)"><frag id="F1"><term sem="DNA_domain_or_region" id="A2">Oct</term></frag> and <frag id="F2"><term sem="DNA_domain_or_region" id="A3">NFAT</term></frag> <frag id="F3"><term sem="DNA_domain_or_region" id="A4">elements</term></frag></cons> <term sem="DNA_domain_or_region" id="A102">within a <term sem="DNA_domain_or_region" id="T4" lex="DNase_I-hypersensitive_site">DNase I-hypersensitive site</term></term>.</sentence>
<event id="E1">
<type class="Positive_regulation" />
<theme idref="A101" />
<cause idref1="A4" idref2="A102" idref="A2" />
<cause idref1="A4" idref2="A102" idref="A3" />
<clue>A T cell-specific enhancer in the interleukin-3 locus is <clueType>activated cooperatively</clueType> <linkCause>by</linkCause> Oct and NFAT elements within a DNase I-hypersensitive site.</clue>
<comment>TPS A101, TPS A102</comment>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term sem="Protein_molecule" id="T5" lex="interleukin-3">Interleukin-3</term> (<term sem="Protein_molecule" id="T6" lex="IL-3">IL-3</term>) is a <term sem="Protein_family_or_group" id="T7" lex="cytokine">cytokine</term> that is expressed primarily in <term sem="Cell_natural" id="T8" lex="activated_T_cell">activated <term sem="Cell_natural" id="A1">T cells</term></term>.</sentence>
<event id="E3">
<type class="Gene_expression" />
<theme idref="T6" />
<clue>Interleukin-3 (IL-3) is a cytokine that is <clueType>expressed</clueType> primarily <clueLoc>in activated T cells</clueLoc>.</clue>
</event>
<event id="E4">
<type class="Physiological_process" />
<theme idref="A1" />
<clue>Interleukin-3 (IL-3) is a cytokine that is expressed primarily in <clueType>activated</clueType> T cells.</clue>
</event>
<sentence id="S3">Here we identified an inducible <term sem="DNA_domain_or_region" id="T9" lex="T_cell-specific_enhancer">T cell-specific enhancer</term> 14 kb upstream of the <term sem="DNA_domain_or_region" id="T10" lex="IL-3_gene"><term sem="Protein_molecule" id="T11" lex="IL-3">IL-3</term> gene</term> that responded to activation of <term sem="Other" id="T12" lex="T_cell_receptor_signaling_pathway"><term sem="Protein_family_or_group" id="T13" lex="T_cell_receptor">T cell receptor</term> signaling pathways</term>.</sentence>
<event id="E5">
<type class="Positive_regulation" />
<theme idref="T10" />
<clue>Here we identified an <clueType>inducible</clueType> <clueLoc>T cell</clueLoc>-specific enhancer 14 kb upstream of the IL-3 gene that responded to activation of T cell receptor signaling pathways.</clue>
</event>
<event id="E6">
<type class="Positive_regulation" />
<theme idref="T12" />
<clue>Here we identified an inducible T cell-specific enhancer 14 kb upstream of the IL-3 gene that responded to <clueType>activation</clueType> <linkTheme>of</linkTheme> T cell receptor signaling pathways.</clue>
</event>
<event id="E7">
<type class="Correlation" />
<theme idref="T10" />
<theme idref="E6" />
<clue>Here we identified an inducible T cell-specific enhancer 14 kb upstream of the IL-3 gene that <clueType>responded</clueType> <linkTheme>to</linkTheme> activation of T cell receptor signaling pathways.</clue>
</event>
<sentence id="S4">The <term sem="DNA_domain_or_region" id="A8"><term sem="Protein_molecule" id="T14" lex="IL-3">IL-3</term> enhancer</term> spanned an inducible <term sem="DNA_domain_or_region" id="T15" lex="cyclosporin_A-sensitive_DNase_I-hypersensitive_site"><term sem="Organic_compound_other" id="T16" lex="cyclosporin_A">cyclosporin A</term>-sensitive <term sem="DNA_domain_or_region" id="T17" lex="DNase_I-hypersensitive_site">DNase I-hypersensitive site</term></term> found only in <term sem="Cell_natural" id="T18" lex="T_cell">T cells</term>.</sentence>
<event id="E8">
<type class="Correlation" />
<theme idref="T16" />
<theme idref="T17" />
<clue>The IL-3 enhancer spanned an inducible cyclosporin A-<clueType>sensitive</clueType> DNase I-hypersensitive site found only <clueLoc>in T cells</clueLoc>.</clue>
<comment>SENSITIVITY</comment>
</event>
<event id="E9">
<type class="Positive_regulation" />
<theme idref="E8" />
<clue>The IL-3 enhancer spanned an <clueType>inducible</clueType> cyclosporin A-sensitive DNase I-hypersensitive site found only <clueLoc>in T cells</clueLoc>.</clue>
</event>
<sentence id="S5">Four <term sem="DNA_family_or_group" id="T19" lex="NFAT-like_element">NFAT-like elements</term> exist within the enhancer.</sentence>
<sentence id="S6">The two most active <term sem="DNA_family_or_group" id="T20" lex="NFAT-like_element">NFAT-like elements</term> were located at the center of the <term sem="DNA_domain_or_region" id="T21" lex="DNase_I-hypersensitive_site">DNase I-hypersensitive site</term>.</sentence>
<event id="E10">
<type class="Positive_regulation" />
<theme idref="T20" />
<clue>The two most <clueType>active</clueType> NFAT-like elements were located at the center of the DNase I-hypersensitive site.</clue>
</event>
<sentence id="S7">One of these <term sem="DNA_family_or_group" id="T22" lex="NFAT-like_element">NFAT-like elements</term> encompassed overlapping <cons sem="(AND DNA_domain_or_region DNA_domain_or_region)" id="T23" lex="(AND Oct-binding_site NFATp/c-binding_site)"><frag id="F4"><term sem="DNA_domain_or_region" id="A5">Oct-</term></frag> and <frag id="F5"><term sem="DNA_domain_or_region" id="A6">NFATp/c-</term></frag><frag id="F6"><term sem="DNA_domain_or_region" id="A7">binding sites</term></frag></cons>, which functioned in a highly synergistic manner.</sentence>
<event id="E11">
<type class="Regulation" />
<cause idref1="A7" idref="A5" />
<cause idref1="A7" idref="A6" />
<clue>One of these NFAT-like elements encompassed overlapping Oct- and NFATp/c-binding sites, which <clueType>functioned</clueType> in a highly <clueType>synergistic</clueType> manner.</clue>
<comment>NO THEME</comment>
</event>
<sentence id="S8">We suggest that the <term sem="Other" id="T24" lex="T_cell-specific_expression">T cell-specific expression</term> of the <term sem="DNA_domain_or_region" id="T25" lex="IL-3_gene"><term sem="Protein_molecule" id="T26" lex="IL-3">IL-3</term> gene</term> is partly controlled through the enhancer by cooperation between <cons sem="(AND Protein_family_or_group Protein_family_or_group)" id="T27" lex="(AND Oct_family_protein NFAT_family_protein)"><frag id="F7"><term sem="Protein_family_or_group" id="A9">Oct</term></frag> and <frag id="F8"><term sem="Protein_family_or_group" id="A10">NFAT</term></frag> <frag id="F9"><term sem="Protein_family_or_group" id="A11">family proteins</term></frag></cons>.</sentence>
<event uncertainty="probable" id="E12">
<type class="Gene_expression" />
<theme idref="T25" />
<clue>We suggest that the <clueLoc>T cell</clueLoc>-specific <clueType>expression</clueType> <linkTheme>of</linkTheme> the IL-3 gene is partly controlled through the enhancer by cooperation between Oct and NFAT family proteins.</clue>
</event>
<event uncertainty="probable" id="E13">
<type class="Regulation" />
<theme idref="E12" />
<cause idref1="A11" idref="A9" />
<cause idref1="A11" idref="A10" />
<clue>We suggest that the T cell-specific expression of the IL-3 gene is partly <clueType>controlled</clueType> through the enhancer <linkCause>by cooperation between</linkCause> Oct and NFAT family proteins.</clue>
</event>
<event uncertainty="probable" id="E14">
<type class="Regulation" />
<theme idref="E13" />
<cause idref="A8" />
<clue>We suggest that the T cell-specific expression of the IL-3 gene is partly controlled <linkCause>through</linkCause> <corefCause>the enhancer</corefCause> by cooperation between Oct and NFAT family proteins.</clue>
<comment>NO CLUETYPE</comment>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/genia-event/original-data/GENIAcorpus_event/8692924.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="20/11/2006" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=8692924" creator="Junko Matsuura">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8692924</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term sem="Protein_molecule" id="T1" lex="BCL-6">BCL-6</term>, a <term sem="Protein_family_or_group" id="T2" lex="POZ/zinc-finger_protein">POZ/zinc-finger protein</term>, is a <term sem="Protein_family_or_group" id="T3" lex="sequence-specific_transcriptional_repressor">sequence-specific transcriptional repressor</term>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">Approximately 40% of <term sem="Other" id="T4" lex="diffuse_large_cell_lymphoma">diffuse large cell lymphoma</term> are associated with <term sem="Other" id="T5" lex="chromosomal_translocation">chromosomal translocations</term> that deregulate the expression of the <term sem="DNA_domain_or_region" id="T6" lex="BCL6_gene">BCL6 gene</term> by juxtaposing <term sem="DNA_domain_or_region" id="T7" lex="heterologous_promoter">heterologous promoters</term> to the <term sem="DNA_domain_or_region" id="T8" lex="BCL-6_coding_domain"><term sem="Protein_molecule" id="T9" lex="BCL-6">BCL-6</term> coding domain</term>.</sentence>
<event id="E1">
<type class="Correlation" />
<theme idref="T4" />
<theme idref="T5" />
<clue>Approximately 40% of diffuse large cell lymphoma are <clueType>associated</clueType> <linkTheme>with</linkTheme> chromosomal translocations that deregulate the expression of the BCL6 gene by juxtaposing heterologous promoters to the BCL-6 coding domain.</clue>
</event>
<event id="E2">
<type class="Gene_expression" />
<theme idref="T6" />
<clue>Approximately 40% of diffuse large cell lymphoma are associated with chromosomal translocations that deregulate the <clueType>expression</clueType> <linkTheme>of</linkTheme> the BCL6 gene by juxtaposing heterologous promoters to the BCL-6 coding domain.</clue>
</event>
<event assertion="non-exist" id="E3">
<type class="Regulation" />
<theme idref="E2" />
<cause idref="T5" />
<clue>Approximately 40% of diffuse large cell lymphoma are associated with chromosomal translocations that <clueType>deregulate</clueType> the expression of the BCL6 gene by juxtaposing heterologous promoters to the BCL-6 coding domain.</clue>
</event>
<sentence id="S3">The <term sem="DNA_domain_or_region" id="T10" lex="BCL6_gene">BCL6 gene</term> encodes a <term sem="Protein_molecule" id="T11" lex="95-kDa_protein">95-kDa protein</term> containing six <term sem="Protein_substructure" id="T12" lex="C-terminal_zinc-finger_motif">C-terminal zinc-finger motifs</term> and an <term sem="Protein_domain_or_region" id="T13" lex="N-terminal_POZ_domain">N-terminal POZ domain</term>, suggesting that it may function as a <term sem="Protein_family_or_group" id="T14" lex="transcription_factor">transcription factor</term>.</sentence>
<sentence id="S4">By using a <term sem="DNA_domain_or_region" id="T15" lex="DNA_sequence">DNA sequence</term> selected for its ability to bind <term sem="Protein_molecule" id="T16" lex="recombinant_BCL-6">recombinant <term sem="Protein_molecule" id="T17" lex="BCL-6">BCL-6</term></term> in vitro, we show here that <term sem="Protein_molecule" id="T18" lex="BCL-6">BCL-6</term> is present in <term sem="Protein_complex" id="T19" lex="DNA-binding_complex">DNA-binding complexes</term> in <term sem="Cell_component" id="T20" lex="nuclear_extract">nuclear extracts</term> from various <term sem="Cell_cultured" id="T21" lex="B-cell_line">B-cell lines</term>.</sentence>
<sentence id="S5">In transient transfectin experiments, <term sem="Protein_molecule" id="T22" lex="BCL6">BCL6</term> can repress <term sem="Other" id="A4">transcription</term> from <term sem="DNA_family_or_group" id="T23" lex="promoter">promoters</term> linked to its <term sem="DNA_domain_or_region" id="T24" lex="DNA_target_sequence">DNA target sequence</term> and this activity is dependent upon specific <term sem="Other" id="T25" lex="DNA-binding">DNA-binding</term> and the presence of an intact <term sem="Protein_domain_or_region" id="T26" lex="N-terminal_half">N-terminal half</term> of the protein.</sentence>
<event id="E4">
<type class="Positive_regulation" />
<theme idref="A4" />
<cause idref="T23" />
<clue>In transient transfectin experiments, BCL6 can repress transcription <linkCause>from</linkCause> promoters linked to its DNA target sequence and this activity is dependent upon specific DNA-binding and the presence of an intact N-terminal half of the protein.</clue>
<comment>NO CLUETYPE</comment>
</event>
<event id="E5">
<type class="Negative_regulation" />
<theme idref="E4" />
<cause idref="T22" />
<clue>In transient transfectin experiments, BCL6 can <clueType>repress</clueType> transcription from promoters linked to its DNA target sequence and this activity is dependent upon specific DNA-binding and the presence of an intact N-terminal half of the protein.</clue>
</event>
<event id="E6">
<type class="Positive_regulation" />
<theme idref="E5" />
<cause idref="T25" />
<clue>In transient transfectin experiments, BCL6 can repress transcription from promoters linked to its DNA target sequence and <corefTheme>this activity</corefTheme> is <clueType>dependent</clueType> <linkCause>upon</linkCause> specific DNA-binding and the presence of an intact N-terminal half of the protein.</clue>
</event>
<event id="E7">
<type class="Positive_regulation" />
<theme idref="E5" />
<cause idref="T26" />
<clue>In transient transfectin experiments, BCL6 can repress transcription from promoters linked to its DNA target sequence and <corefTheme>this activity</corefTheme> is <clueType>dependent</clueType> <linkCause>upon</linkCause> specific DNA-binding and the presence of an intact N-terminal half of the protein.</clue>
</event>
<sentence id="S6">We demonstrate that this part of the <term sem="Protein_molecule" id="T27" lex="BCL6_molecule"><term sem="Protein_molecule" id="T28" lex="BCL6">BCL6</term> molecule</term> contains an <term sem="Protein_domain_or_region" id="T29" lex="autonomous_transrepressor_domain">autonomous transrepressor domain</term> and that two <term sem="Protein_domain_or_region" id="T30" lex="noncontiguous_regions">noncontiguous regions</term>, including the <term sem="Protein_substructure" id="T31" lex="POZ_motif">POZ motif</term>, mediate maximum <term sem="Other" id="T32" lex="transrepressive_activity">transrepressive activity</term>.</sentence>
<event id="E8">
<type class="Positive_regulation" />
<theme idref="T32" />
<cause idref="T30" />
<clue>We demonstrate that this part of the BCL6 molecule contains an autonomous transrepressor domain and that two noncontiguous regions, including the POZ motif, <clueType>mediate</clueType> maximum transrepressive activity.</clue>
</event>
<sentence id="S7">These results indicate that the <term sem="Protein_molecule" id="T33" lex="BCL-6_protein"><term sem="Protein_molecule" id="T34" lex="BCL-6">BCL-6</term> protein</term> can function as a <term sem="Protein_family_or_group" id="T35" lex="sequence-specific_transcriptional_repressor">sequence-specific transcriptional repressor</term> and have implications for the role of <term sem="Protein_molecule" id="T36" lex="BCL6">BCL6</term> in <term sem="Other" id="T37" lex="normal_lymphoid_development">normal <term sem="Cell_natural" id="A3">lymphoid</term> development</term> and <term sem="Other" id="T38" lex="lymphomagenesis">lymphomagenesis</term>.</sentence>
<event id="E9">
<type class="Cellular_physiological_process" />
<theme idref="A3" />
<clue>These results indicate that the BCL-6 protein can function as a sequence-specific transcriptional repressor and have implications for the role of BCL6 in normal lymphoid <clueType>development</clueType> and lymphomagenesis.</clue>
</event>
<event uncertainty="probable" id="E10">
<type class="Positive_regulation" />
<theme idref="E9" />
<cause idref="T36" />
<clue>These results indicate that the BCL-6 protein can function as a sequence-specific transcriptional repressor and have implications for the <clueType>role</clueType> <linkCause>of</linkCause> BCL6 <linkTheme>in</linkTheme> normal lymphoid development and lymphomagenesis.</clue>
</event>
<event uncertainty="probable" id="E11">
<type class="Positive_regulation" />
<theme idref="E9" />
<cause idref="T38" />
<clue>These results indicate that the BCL-6 protein can function as a sequence-specific transcriptional repressor and have implications for the <clueType>role</clueType> <linkCause>of</linkCause> BCL6 <linkTheme>in</linkTheme> normal lymphoid development and lymphomagenesis.</clue>
</event>
<event id="E12">
<type class="Negative_regulation" />
<cause idref="T33" />
<clue>These results indicate that the BCL-6 protein can <clueType>function as</clueType> a sequence-specific <clueType>transcriptional repressor</clueType> and have implications for the role of BCL6 in normal lymphoid development and lymphomagenesis.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/genia-event/original-data/GENIAcorpus_event/1531412.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="13/11/2006" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=1531412" creator="Noriko Katsu">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>1531412</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term sem="Other" id="T1" lex="transcriptional_regulation">Transcriptional regulation</term> during <term sem="Other" id="T2" lex="T-cell_development"><term sem="Cell_natural" id="T3" lex="T-cell">T-cell</term> development</term>: the <term sem="DNA_domain_or_region" id="T4" lex="alpha_TCR_gene">alpha TCR gene</term> as a <term sem="Other" id="T5" lex="molecular_model">molecular model</term>.</sentence>
<event id="E1">
<type class="Regulation" />
<theme idref="E4" />
<clue>Transcriptional <clueType>regulation</clueType> during T-cell development: the alpha TCR gene as a molecular model.</clue>
</event>
<event id="E2">
<type class="Correlation" />
<theme idref="E1" />
<theme idref="E3" />
<clue>Transcriptional regulation <linkTheme>during</linkTheme> T-cell development: the alpha TCR gene as a molecular model.</clue>
</event>
<event id="E3">
<type class="Cell_differentiation" />
<theme idref="T3" />
<clue>Transcriptional regulation during T-cell <clueType>development</clueType>: the alpha TCR gene as a molecular model.</clue>
</event>
<event id="E4">
<type class="Transcription" />
<theme idref="T4" />
<clue><clueType>Transcriptional</clueType> regulation during T-cell development: the alpha TCR gene as a molecular model.</clue>
<comment>CAUTION: THEME from the context</comment>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The regulation of <term sem="Other" id="T6" lex="gene_expression">gene expression</term> during <term sem="Other" id="T7" lex="lymphocyte_differentiation"><term sem="Cell_natural" id="T8" lex="lymphocyte">lymphocyte</term> differentiation</term> is a complex process involving interactions between <cons sem="(AND DNA_domain_or_region DNA_domain_or_region)" id="T9" lex="(AND multiple_positive_transcriptional_regulatory_element multiple_negative_transcriptional_regulatory_element)"><frag id="F1">multiple</frag> <frag id="F2">positive</frag> and <frag id="F3">negative</frag> <frag id="F4">transcriptional regulatory elements</frag></cons>.</sentence>
<event id="E6">
<type class="Regulation" />
<theme idref="T6" />
<cause idref="E10" />
<clue>The <clueType>regulation</clueType> <linkTheme>of</linkTheme> gene expression <clueTime>during lymphocyte differentiation</clueTime> is a complex process <linkCause>involving</linkCause> interactions between multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<event id="E8">
<type class="Cell_differentiation" />
<theme idref="T8" />
<clue>The regulation of gene expression during lymphocyte <clueType>differentiation</clueType> is a complex process involving interactions between multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<event id="E9">
<type class="Regulation" />
<theme idref="E6" />
<cause idref="E10" />
<clue>The regulation of gene expression during lymphocyte differentiation is a complex process <clueType>involving</clueType> interactions between multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<event id="E10">
<type class="Correlation" />
<theme idref1="F4" idref="F2" />
<theme idref1="F4" idref="F3" />
<clue>The regulation of gene expression during lymphocyte differentiation is a complex process involving <clueType>interactions</clueType> <linkTheme>between</linkTheme> multiple positive and negative transcriptional regulatory elements.</clue>
</event>
<sentence id="S3">In this article, <term sem="Other" id="T10" lex="transcriptional_regulation">transcriptional regulation</term> of the <term sem="DNA_domain_or_region" id="T11" lex="archetypal_T-cell-specific_gene">archetypal <term sem="Cell_natural" id="T12" lex="T-cell">T-cell</term>-specific gene</term>, <term sem="DNA_domain_or_region" id="T13" lex="alpha_TCR">alpha TCR</term>, is discussed.</sentence>
<event id="E13">
<type class="Regulation" />
<theme idref="T13" />
<clue>In this article, <clueType>transcriptional regulation</clueType> <linkTheme>of</linkTheme> the archetypal T-cell-specific gene, alpha TCR, is discussed.</clue>
</event>
<sentence id="S4">Major recent developments, including the identification of novel families of <term sem="Protein_family_or_group" id="T14" lex="transcription_factor">transcription factors</term> that regulate multiple <term sem="DNA_family_or_group" id="T15" lex="T-cell_gene"><term sem="Cell_natural" id="T16" lex="T-cell">T-cell</term> genes</term> during <term sem="Other" id="T17" lex="thymocyte_ontogeny">thymocyte ontogeny</term> and <term sem="Other" id="T18" lex="T-cell_activation"><term sem="Cell_natural" id="T19" lex="T-cell">T-cell</term> activation</term>, are described.</sentence>
<event id="E15">
<type class="Regulation" />
<theme idref="T15" />
<cause idref="T14" />
<clue>Major recent developments, including the identification of novel families of transcription factors that <clueType>regulate</clueType> multiple <clueLoc>T-cell</clueLoc> genes during thymocyte ontogeny and T-cell activation, are described.</clue>
<comment>NER: T14 sem mod, DNA_domain_or_region -&gt; Protein_family_or_group</comment>
</event>
<event id="E16">
<type class="Correlation" />
<theme idref="E15" />
<theme idref="T17" />
<clue>Major recent developments, including the identification of novel families of transcription factors that regulate multiple T-cell genes <linkTheme>during</linkTheme> thymocyte ontogeny and T-cell activation, are described.</clue>
</event>
<event id="E17">
<type class="Correlation" />
<theme idref="E15" />
<theme idref="E18" />
<clue>Major recent developments, including the identification of novel families of transcription factors that regulate multiple T-cell genes <linkTheme>during</linkTheme> thymocyte ontogeny and T-cell activation, are described.</clue>
</event>
<event id="E18">
<type class="Physiological_process" />
<theme idref="T19" />
<clue>Major recent developments, including the identification of novel families of transcription factors that regulate multiple T-cell genes during thymocyte ontogeny and T-cell <clueType>activation</clueType>, are described.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
