=== Beira-BF/genia-event/original-data/GENIAtypes/GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term&event annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: 9 January 2008                    -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Other
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID			#REQUIRED
>

<!ELEMENT frag		(#PCDATA | term)*>
<!ATTLIST frag
		id  ID		#REQUIRED
>
<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, theme*, site*, product*, cause*, clue, comment?)>
<!ATTLIST event
		id		ID				#REQUIRED
		assertion	(exist|non-exist)		"exist"
		uncertainty 	(certain|probable|doubtful)	"certain"
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | corefTheme | corefSite | corefProduct | corefCause | clueExperiment)*>

<!ELEMENT clueType		(#PCDATA)>
<!ELEMENT linkTheme		(#PCDATA)>
<!ELEMENT linkCause		(#PCDATA)>
<!ELEMENT clueTime		(#PCDATA)>
<!ELEMENT clueLoc		(#PCDATA)>
<!ELEMENT clueExperiment	(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA)>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA)>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

=== Beira-BF/genia-event/original-data/GENIAcorpus_event/8184011.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="02/05/2006" creator="Junko Matsuura" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=8184011">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8184011</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Activation of <term sem="Protein_molecule" id="T1" lex="nuclear_factor_kappa_B">nuclear factor kappa B</term> in <term sem="Cell_natural" id="T2" lex="human_lymphoblastoid_cell">human lymphoblastoid cells</term> by <term sem="Other" id="T3" lex="low-dose_ionizing_radiation">low-dose ionizing radiation</term>.</sentence>
<event id="E1">
<type class="Positive_regulation" />
<theme idref="T1" />
<cause idref="T3" />
<clue><clueType>Activation</clueType> <linkTheme>of</linkTheme> nuclear factor kappa B <clueLoc>in human lymphoblastoid cells</clueLoc> <linkCause>by</linkCause> low-dose ionizing radiation.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term sem="Protein_molecule" id="T4" lex="nuclear_factor_kappa_B">Nuclear factor kappa B</term> (<term sem="Protein_molecule" id="T5" lex="NF-kappa_B">NF-kappa B</term>) is a <term sem="Protein_family_or_group" id="T6" lex="pleiotropic_transcription_factor">pleiotropic transcription factor</term> which is involved in the <term sem="Other" id="T7" lex="transcriptional_regulation">transcriptional regulation</term> of several specific genes.</sentence>
<event id="E3">
<type class="Correlation" />
<theme idref="T7" />
<theme idref="T5" />
<clue>Nuclear factor kappa B (NF-kappa B) is a pleiotropic transcription factor which is <clueType>involved</clueType> <linkTheme>in</linkTheme> the transcriptional regulation of several specific genes.</clue>
</event>
<sentence id="S3">Recent reports demonstrated that <term sem="Other" id="T8" lex="ionizing_radiation">ionizing radiation</term> in the dose range of <term sem="Other" id="T9" lex="2-50_Gy">2-50 Gy</term> results in expression of <term sem="Protein_molecule" id="T10" lex="NF-kappa_B">NF-kappa B</term> in <term sem="Cell_cultured" id="T11" lex="human_KG-1_myeloid_leukemia_cell">human KG-1 myeloid leukemia cells</term> and <term sem="Cell_natural" id="T12" lex="human_B-lymphocyte_precursor_cell">human B-lymphocyte precursor cells</term>; the precise mechanism involved and the significance are not yet known.</sentence>
<event id="E4">
<type class="Gene_expression" />
<theme idref="T10" />
<clue>Recent reports demonstrated that ionizing radiation in the dose range of 2-50 Gy results in <clueType>expression</clueType> <linkTheme>of</linkTheme> NF-kappa B in human KG-1 myeloid leukemia cells and human B-lymphocyte precursor cells; the precise mechanism involved and the significance are not yet known.</clue>
</event>
<event id="E300">
<type class="Positive_regulation" />
<theme idref="E4" />
<cause idref="T8" />
<clue>Recent reports demonstrated that ionizing radiation in the dose range of 2-50 Gy <clueType>results</clueType> <linkTheme>in</linkTheme> expression of NF-kappa B <clueLoc>in human KG-1 myeloid leukemia cells</clueLoc> and human B-lymphocyte precursor cells; the precise mechanism involved and the significance are not yet known.</clue>
</event>
<event id="E301">
<type class="Positive_regulation" />
<theme idref="E4" />
<cause idref="T8" />
<clue>Recent reports demonstrated that ionizing radiation in the dose range of 2-50 Gy <clueType>results</clueType> <linkTheme>in</linkTheme> expression of NF-kappa B <clueLoc>in</clueLoc> human KG-1 myeloid leukemia cells and <clueLoc>human B-lymphocyte precursor cells</clueLoc>; the precise mechanism involved and the significance are not yet known.</clue>
</event>
<sentence id="S4">The present report demonstrates that even lower doses of <term sem="Other" id="T13" lex="ionizing_radiation">ionizing radiation</term>, <term sem="Other" id="T14" lex="0.25-2.0_Gy">0.25-2.0 Gy</term>, are capable of inducing expression of <term sem="Protein_molecule" id="T15" lex="NF-kappa_B">NF-kappa B</term> in <term sem="Cell_cultured" id="T16" lex="EBV-transformed_244B_human_lymphoblastoid_cell">EBV-transformed 244B <term sem="Cell_natural" id="T17" lex="human_lymphoblastoid_cell">human lymphoblastoid cells</term></term>.</sentence>
<event id="E6">
<type class="Gene_expression" />
<theme idref="T15" />
<clue>The present report demonstrates that even lower doses of ionizing radiation, 0.25-2.0 Gy, are capable of inducing <clueType>expression</clueType> <linkTheme>of</linkTheme> NF-kappa B in EBV-transformed 244B human lymphoblastoid cells.</clue>
</event>
<event id="E7">
<type class="Positive_regulation" />
<theme idref="E6" />
<cause idref="T13" />
<clue>The present report demonstrates that even lower doses of ionizing radiation, 0.25-2.0 Gy, are capable of <clueType>inducing</clueType> expression of NF-kappa B <clueLoc>in EBV-transformed 244B human lymphoblastoid cells</clueLoc>.</clue>
</event>
<sentence id="S5">These results are in a dose range where the viability of the cells remains very high.</sentence>
<sentence id="S6">After exposure to <term sem="Other" id="T18" lex="137Cs_gamma_ray">137Cs gamma rays</term> at a dose rate of <term sem="Other" id="T19" lex="1.17_Gy/min">1.17 Gy/min</term>, a maximum in expression of <term sem="Protein_molecule" id="T20" lex="NF-kappa_B">NF-kappa B</term> was seen at 8 h after a <term sem="Other" id="T21" lex="0.5-Gy_exposure">0.5-Gy exposure</term>.</sentence>
<event id="E9">
<type class="Gene_expression" />
<theme idref="T20" />
<clue>After exposure to 137Cs gamma rays at a dose rate of 1.17 Gy/min, a maximum in <clueType>expression</clueType> <linkTheme>of</linkTheme> NF-kappa B was seen at 8 h after a 0.5-Gy exposure.</clue>
</event>
<event id="E10">
<type class="Positive_regulation" />
<theme idref="E9" />
<cause idref="T18" />
<clue><linkCause>After</linkCause> exposure to 137Cs gamma rays at a dose rate of 1.17 Gy/min, a maximum in expression of NF-kappa B was <clueType>seen</clueType> <clueTime>at 8 h after a 0.5-Gy exposure</clueTime>.</clue>
</event>
<sentence id="S7">Time-course studies revealed a <term sem="Other" id="A2">biphasic time-dependent expression</term> after <term sem="Other" id="T22" lex="0.5-,_1-_and_2-Gy_exposure">0.5-, 1- and 2-Gy exposures</term>.</sentence>
<event id="E11">
<type class="Positive_regulation" />
<theme idref="A2" />
<cause idref="T22" />
<clue><clueExperiment>Time-course studies</clueExperiment> <clueType>revealed</clueType> a biphasic time-dependent expression <clueTime>after</clueTime> 0.5-, 1- and 2-Gy exposures.</clue>
</event>
<sentence id="S8">However, for each time examined, the expression of <term sem="Protein_molecule" id="T23" lex="NF-kappa_B">NF-kappa B</term> was maximum after the <term sem="Other" id="T24" lex="0.5-Gy_exposure">0.5-Gy exposure</term>.</sentence>
<event id="E12">
<type class="Gene_expression" />
<theme idref="T23" />
<clue>However, for each time examined, the <clueType>expression</clueType> <linkTheme>of</linkTheme> NF-kappa B was maximum after the 0.5-Gy exposure.</clue>
</event>
<event id="E13">
<type class="Positive_regulation" />
<theme idref="E12" />
<cause idref="T24" />
<clue>However, for each time examined, the expression of NF-kappa B <clueType>was maximum</clueType> <linkCause>after</linkCause> the 0.5-Gy exposure.</clue>
</event>
<sentence id="S9">The expression of the <cons sem="(AND Protein_molecule Protein_molecule)" id="T25" lex="(AND p50_NF-kappa_B_subunit p65_NF-kappa_B_subunit)"><frag id="F1"><term sem="Protein_molecule" id="A20">p50</term></frag> and <frag id="F2"><term sem="Protein_molecule" id="A21">p65</term></frag> <frag id="F3">NF-kappa B subunits</frag></cons> was also shown to be regulated differentially after exposures to <term sem="Other" id="T26" lex="1.0_and_2.0_Gy">1.0 and 2.0 Gy</term>.</sentence>
<event id="E14">
<type class="Gene_expression" />
<theme idref="A20" />
<clue>The <clueType>expression</clueType> of the p50 and p65 NF-kappa B subunits was also shown to be regulated differentially after exposures to 1.0 and 2.0 Gy.</clue>
</event>
<event id="E15">
<type class="Gene_expression" />
<theme idref="A21" />
<clue>The <clueType>expression</clueType> of the p50 and p65 NF-kappa B subunits was also shown to be regulated differentially after exposures to 1.0 and 2.0 Gy.</clue>
</event>
<event id="E16">
<type class="Regulation" />
<theme idref="E14" />
<cause idref="T26" />
<clue>The expression of the p50 and p65 NF-kappa B subunits was also shown to be <clueType>regulated</clueType> differentially <linkCause>after</linkCause> exposures to 1.0 and 2.0 Gy.</clue>
</event>
<event id="E17">
<type class="Regulation" />
<theme idref="E15" />
<cause idref="T26" />
<clue>The expression of the p50 and p65 NF-kappa B subunits was also shown to be <clueType>regulated</clueType> differentially <linkCause>after</linkCause> exposures to 1.0 and 2.0 Gy.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/genia-event/original-data/GENIAcorpus_event/1700011.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="14/03/2007" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=1700011" creator="Junko Matsuura">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>1700011</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term sem="Protein_molecule" id="T1" lex="NF-X2">NF-X2</term> that binds to the <term sem="DNA_domain_or_region" id="T2" lex="DRA_X2-box">DRA X2-box</term> is <term sem="Protein_molecule" id="T3" lex="activator_protein_1">activator protein 1</term>.</sentence>
<event id="E1">
<type class="Binding" />
<theme idref="T1" />
<theme idref="T2" />
<clue>NF-X2 that <clueType>binds</clueType> <linkTheme>to</linkTheme> the DRA X2-box is activator protein 1.</clue>
</event>
<event id="E2">
<type class="Binding" />
<theme idref="T3" />
<theme idref="T2" />
<clue>NF-X2 that <clueType>binds</clueType> <linkTheme>to</linkTheme> the DRA X2-box is activator protein 1.</clue>
</event>
<sentence id="S2"><term sem="Other" id="T4" lex="expression_cloning">Expression cloning</term> of <term sem="Protein_molecule" id="T5" lex="c-Jun">c-Jun</term>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="Protein_family_or_group" id="T6" lex="human_class_II_MHC_Ag">Human class II MHC Ag</term> are a family of <term sem="Protein_domain_or_region" id="T7" lex="cell_surface_glycoprotein">cell surface glycoproteins</term>.</sentence>
<sentence id="S4">Their constitutive expression is limited to <term sem="Cell_natural" id="T8" lex="B_lymphocyte">B lymphocytes</term> and <term sem="Cell_natural" id="T9" lex="thymic_epithelial_cell">thymic epithelial cells</term>.</sentence>
<event id="E300">
<type class="Gene_expression" />
<theme idref="T6" />
<clue><corefTheme>Their</corefTheme> constitutive <clueType>expression</clueType> is limited to <clueLoc>B lymphocytes</clueLoc> and thymic epithelial cells.</clue>
</event>
<event id="E301">
<type class="Gene_expression" />
<theme idref="T6" />
<clue><corefTheme>Their</corefTheme> constitutive <clueType>expression</clueType> is limited to B lymphocytes and <clueLoc>thymic epithelial cells</clueLoc>.</clue>
</event>
<sentence id="S5">In many other cells their <term sem="Other" id="T10" lex="expression">expression</term> can be induced by <term sem="Protein_molecule" id="T11" lex="IFN-gamma">IFN-gamma</term>.</sentence>
<event id="E4">
<type class="Gene_expression" />
<theme idref="T6" />
<clue>In many other cells <corefTheme>their</corefTheme> <clueType>expression</clueType> can be induced by IFN-gamma.</clue>
</event>
<event id="E5">
<type class="Positive_regulation" />
<theme idref="E4" />
<cause idref="T11" />
<clue><clueLoc>In many other cells</clueLoc> their expression can be <clueType>induced</clueType> <linkCause>by</linkCause> IFN-gamma.</clue>
</event>
<sentence id="S6"><term sem="DNA_domain_or_region" id="A1">Conserved upstream promoter sequences</term> regulate this tissue-specific expression of <term sem="DNA_family_or_group" id="T12" lex="class_II_gene">class II genes</term>.</sentence>
<event id="E302">
<type class="Regulation" />
<theme idref="E300" />
<cause idref="A1" />
<clue>Conserved upstream promoter sequences <clueType>regulate</clueType> <corefTheme>this tissue-specific expression of class II genes.</corefTheme></clue>
</event>
<event id="E303">
<type class="Regulation" />
<theme idref="E301" />
<cause idref="A1" />
<clue>Conserved upstream promoter sequences <clueType>regulate</clueType> <corefTheme>this tissue-specific expression of class II genes.</corefTheme></clue>
</event>
<event id="E7">
<type class="Regulation" />
<theme idref="E5" />
<cause idref="A1" />
<clue>Conserved upstream promoter sequences <clueType>regulate</clueType> <corefTheme>this tissue-specific expression of class II genes.</corefTheme></clue>
</event>
<sentence id="S7">In the <term sem="DNA_domain_or_region" id="T13" lex="DRA_promoter">DRA promoter</term>, one of these <term sem="DNA_domain_or_region" id="T14" lex="cis-acting_regulatory_motif">cis-acting regulatory motifs</term> is the <term sem="DNA_domain_or_region" id="T15" lex="X2-box">X2-box</term> to which <term sem="Protein_molecule" id="T16" lex="nuclear_factor_X2">nuclear factor X2</term> (<term sem="Protein_molecule" id="T17" lex="NF-X2">NF-X2</term>) binds.</sentence>
<event id="E8">
<type class="Binding" />
<theme idref="T17" />
<theme idref="T15" />
<clue>In the DRA promoter, one of these cis-acting regulatory motifs is the X2-box <linkTheme>to</linkTheme> which nuclear factor X2 (NF-X2) <clueType>binds</clueType>.</clue>
</event>
<sentence id="S8">Here, we present the isolation and characterization of the <term sem="DNA_family_or_group" id="T18" lex="full-length_cDNA_clone">full-length cDNA clone</term> encoding <term sem="Protein_molecule" id="T19" lex="NF-X2">NF-X2</term>.</sentence>
<sentence id="S9">This <term sem="DNA_molecule" id="T20" lex="cDNA_clone">cDNA clone</term> was isolated by <term sem="Other" id="T21" lex="expression_cDNA_cloning">expression <term sem="DNA_family_or_group" id="T22" lex="cDNA">cDNA</term> cloning</term>, and encodes the <term sem="Protein_molecule" id="T23" lex="human_c-Jun_protein">human <term sem="Protein_molecule" id="T24" lex="c-Jun">c-Jun</term> protein</term>, which together with <term sem="Protein_molecule" id="T25" lex="c-Fos">c-Fos</term> forms the <term sem="Protein_family_or_group" id="T26" lex="heterodimeric_activator_protein-1_transcription_complex">heterodimeric activator protein-1 transcription complex</term>.</sentence>
<event id="E9">
<type class="Binding" />
<theme idref="T25" />
<theme idref="T24" />
<clue>This cDNA clone was isolated by expression cDNA cloning, and encodes the human c-Jun protein, which <linkTheme>together with</linkTheme> c-Fos <clueType>forms the heterodimeric</clueType> activator protein-1 transcription <clueType>complex</clueType>.</clue>
</event>
<event id="E19">
<type class="Protein_metabolism" />
<theme idref="T26" />
<clue>This cDNA clone was isolated by expression cDNA cloning, and encodes the human c-Jun protein, which together with c-Fos <clueType>forms the heterodimeric</clueType> activator protein-1 transcription <clueType>complex</clueType>.</clue>
</event>
<sentence id="S10">Whereas <term sem="Protein_complex" id="T27" lex="c-Fos/c-Jun_heterodimer"><term sem="Protein_molecule" id="T28" lex="c-Fos">c-Fos</term><term sem="Protein_molecule" id="T29" lex="c-Jun">/c-Jun</term> heterodimers</term> do not exist in <term sem="Cell_cultured" id="T30" lex="B_cell">B cells</term>, they form and bind to the <term sem="DNA_domain_or_region" id="T31" lex="X2-box">X2-box</term> in <term sem="Cell_cultured" id="T32" lex="class_II_nonexpressing_cell">class II nonexpressing cells</term>.</sentence>
<event assertion="non-exist" id="E10">
<type class="Gene_expression" />
<theme idref="T27" />
<clue>Whereas c-Fos/c-Jun heterodimers do not <clueType>exist</clueType> <clueLoc>in B cells</clueLoc>, they form and bind to the X2-box in class II nonexpressing cells.</clue>
</event>
<event id="E11">
<type class="Binding" />
<theme idref="T28" />
<theme idref="T29" />
<clue>Whereas c-Fos/c-Jun <clueType>heterodimers</clueType> do not exist in B cells, they <clueType>form</clueType> and bind to the X2-box <clueLoc>in class II nonexpressing cells</clueLoc>.</clue>
</event>
<event id="E12">
<type class="Binding" />
<theme idref="T27" />
<theme idref="T31" />
<clue>Whereas c-Fos/c-Jun heterodimers do not exist in B cells, they form and <clueType>bind</clueType> <linkTheme>to</linkTheme> the X2-box <clueLoc>in class II nonexpressing cells</clueLoc>.</clue>
</event>
<sentence id="S11">Thus, <term sem="Protein_complex" id="T33" lex="c-Fos/c-Jun_heterodimer"><term sem="Protein_molecule" id="T34" lex="c-Fos">c-Fos</term><term sem="Protein_molecule" id="T35" lex="c-Jun">/c-Jun</term> heterodimers</term> might contribute to the repression of <term sem="Other" id="T36" lex="DRA_gene_expression"><term sem="DNA_domain_or_region" id="T37" lex="DRA_gene">DRA gene</term> expression</term>.</sentence>
<event id="E13">
<type class="Gene_expression" />
<theme idref="T37" />
<clue>Thus, c-Fos/c-Jun heterodimers might contribute to the repression of DRA gene <clueType>expression</clueType>.</clue>
</event>
<event uncertainty="probable" id="E14">
<type class="Negative_regulation" />
<theme idref="E13" />
<cause idref="T33" />
<clue>Thus, c-Fos/c-Jun heterodimers might contribute to the <clueType>repression</clueType> <linkTheme>of</linkTheme> DRA gene expression.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
