=== Beira-BF/genia-event/original-data/GENIAtypes/GENIA_event_20.dtd
<!-- ============================================================ -->
<!-- DTD for Genia corpus with term&event annotation              -->
<!-- written by Jin-Dong KIM <jdkim@tsujii.is.s.u-tokyo.ac.jp>    -->
<!-- Date of last modification: 9 January 2008                    -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for term&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
Element | Inorganic_compound | Organic_compound_other |
Amino_acid_monomer | Peptide | Carbohydrate | Lipid |
Protein_complex | Protein_domain_or_region | Protein_family_or_group |
Protein_molecule | Protein_substructure |
DNA_domain_or_region | DNA_family_or_group | DNA_molecule | DNA_substructure |
RNA_domain_or_region | RNA_family_or_group | RNA_molecule | RNA_substructure |
Nucleotide | Polynucleotide |
Cell_component | Cell_cultured | Cell_natural |
Body_region | Tissue_cultured | Tissue_natural |
Multicellular_organism_natural | Multicellular_organism_genetically_modified |
Unicellular_organism | Virus | Other
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | cons | term | frag)*>
<!ATTLIST sentence	id ID	#REQUIRED>

<!ELEMENT cons		(#PCDATA | cons | term | frag)*>
<!ATTLIST cons 
		sem CDATA #REQUIRED
		lex CDATA #REQUIRED
		id  ID    #REQUIRED
>

<!ELEMENT term		(#PCDATA | term | frag)*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID			#REQUIRED
>

<!ELEMENT frag		(#PCDATA | term)*>
<!ATTLIST frag
		id  ID		#REQUIRED
>
<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, theme*, site*, product*, cause*, clue, comment?)>
<!ATTLIST event
		id		ID				#REQUIRED
		assertion	(exist|non-exist)		"exist"
		uncertainty 	(certain|probable|doubtful)	"certain"
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">

<!ELEMENT theme EMPTY>
<!ATTLIST theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT site EMPTY>
<!ATTLIST site
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT product EMPTY>
<!ATTLIST product
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT cause EMPTY>
<!ATTLIST cause
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
>

<!ELEMENT clue  (#PCDATA | clueType | linkTheme | linkCause | clueTime | clueLoc | corefTheme | corefSite | corefProduct | corefCause | clueExperiment)*>

<!ELEMENT clueType		(#PCDATA)>
<!ELEMENT linkTheme		(#PCDATA)>
<!ELEMENT linkCause		(#PCDATA)>
<!ELEMENT clueTime		(#PCDATA)>
<!ELEMENT clueLoc		(#PCDATA)>
<!ELEMENT clueExperiment	(#PCDATA)>

<!ELEMENT corefTheme		(#PCDATA)>
<!ATTLIST corefTheme
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefCause		(#PCDATA)>
<!ATTLIST corefCause
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefSite		(#PCDATA)>
<!ATTLIST corefSite
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT corefProduct		(#PCDATA)>
<!ATTLIST corefProduct
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT comment		(#PCDATA)>

=== Beira-BF/genia-event/original-data/GENIAcorpus_event/9144218.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="13/11/2006" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9144218" creator="Yo Shidahara">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9144218</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">An <term sem="DNA_domain_or_region" id="T1" lex="enhancer-blocking_element">enhancer-blocking element</term> between <cons sem="(AND DNA_domain_or_region DNA_domain_or_region)" id="T2" lex="(AND alpha_gene_segment delta_gene_segment)"><frag id="F1">alpha</frag> and <frag id="F2">delta</frag> <frag id="F3">gene segments</frag></cons> within the <term sem="DNA_domain_or_region" id="T3" lex="human_T_cell_receptor_alpha/delta_locus">human T cell receptor alpha/delta locus</term>.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2"><term sem="DNA_domain_or_region" id="T4" lex="T_cell_receptor_(TCR)_alpha">T cell receptor (TCR)</term> <term sem="DNA_domain_or_region" id="A1">alpha</term> and <term sem="DNA_domain_or_region" id="A2">delta</term> <term sem="DNA_domain_or_region" id="A3">gene</term> segments are organized within a single genetic locus but are differentially regulated during <term sem="Other" id="T5" lex="T_cell_development"><term sem="Cell_natural" id="A4">T cell</term> development</term>.</sentence>
<event id="E1">
<type class="Regulation" />
<theme idref1="A1" idref2="A3" idref="T4" />
<clue>T cell receptor (TCR) alpha and delta gene segments are organized within a single genetic locus but are differentially <clueType>regulated</clueType> <clueTime>during T cell development</clueTime>.</clue>
<comment>NER T4 MOD</comment>
</event>
<event id="E2">
<type class="Regulation" />
<theme idref1="A2" idref2="A3" idref="T4" />
<clue>T cell receptor (TCR) alpha and delta gene segments are organized within a single genetic locus but are differentially <clueType>regulated</clueType> <clueTime>during T cell development</clueTime>.</clue>
</event>
<sentence id="S3">An <term sem="DNA_domain_or_region" id="T6" lex="enhancer-blocking_element">enhancer-blocking element</term> (<term sem="DNA_domain_or_region" id="T7" lex="BEAD-1">BEAD-1</term>, for blocking <term sem="DNA_domain_or_region" id="T8" lex="element_alpha/delta_1">element alpha/delta 1</term>) was localized to a <term sem="DNA_domain_or_region" id="T9" lex="2.0-kb_region">2.0-kb region</term> 3&apos; of <term sem="DNA_domain_or_region" id="T10" lex="TCR_delta_gene_segment">TCR delta gene segments</term> and 5&apos; of <term sem="DNA_domain_or_region" id="T11" lex="TCR_alpha_joining_gene_segment">TCR alpha joining gene segments</term> within this locus.</sentence>
<event id="E3">
<type class="Negative_regulation" />
<theme idref="T8" />
<cause idref="T7" />
<clue>An enhancer-blocking element (BEAD-1, <linkCause>for</linkCause> <clueType>blocking</clueType> element alpha/delta 1) was localized to a 2.0-kb region 3&apos; of TCR delta gene segments and 5&apos; of TCR alpha joining gene segments within this locus.</clue>
</event>
<sentence id="S4"><term sem="DNA_domain_or_region" id="T12" lex="BEAD-1">BEAD-1</term> blocked the ability of the <term sem="DNA_domain_or_region" id="T13" lex="TCR_delta_enhancer">TCR delta enhancer</term> (<term sem="DNA_domain_or_region" id="T14" lex="Edelta">Edelta</term>) to activate a <term sem="DNA_family_or_group" id="A5">promoter</term> when located between the two in a <term sem="DNA_family_or_group" id="T15" lex="chromatin-integrated_construct">chromatin-integrated construct</term>.</sentence>
<event id="E4">
<type class="Positive_regulation" />
<theme idref="A5" />
<cause idref="T14" />
<clue>BEAD-1 blocked the ability of the TCR delta enhancer (Edelta) to <clueType>activate</clueType> a promoter when located between the two in a chromatin-integrated construct.</clue>
</event>
<event id="E5">
<type class="Negative_regulation" />
<theme idref="E4" />
<cause idref="E6" />
<clue>BEAD-1 <clueType>blocked</clueType> the ability of the TCR delta enhancer (Edelta) to activate a promoter <linkCause>when</linkCause> located between the two in a chromatin-integrated construct.</clue>
</event>
<event id="E6">
<type class="Artificial_process" />
<theme idref="T12" />
<clue>BEAD-1 blocked the ability of the TCR delta enhancer (Edelta) to activate a promoter when <clueType>located</clueType> <clueLoc>between the two in a chromatin-integrated construct</clueLoc>.</clue>
</event>
<sentence id="S5">We propose that <term sem="DNA_domain_or_region" id="T16" lex="BEAD-1">BEAD-1</term> functions as a boundary that separates the <term sem="DNA_domain_or_region" id="T17" lex="TCR_alpha/delta_locus">TCR alpha/delta locus</term> into distinct <term sem="DNA_domain_or_region" id="T18" lex="regulatory_domain">regulatory domains</term> controlled by <term sem="DNA_domain_or_region" id="T19" lex="Edelta">Edelta</term> and the <term sem="DNA_domain_or_region" id="T20" lex="TCR_alpha_enhancer">TCR alpha enhancer</term>, and that it prevents <term sem="DNA_domain_or_region" id="T21" lex="Edelta">Edelta</term> from opening the <term sem="DNA_family_or_group" id="T22" lex="chromatin">chromatin</term> of the <term sem="DNA_domain_or_region" id="T23" lex="TCR_alpha">TCR alpha joining gene segments</term> for <term sem="Other" id="T24" lex="VDJ_recombination">VDJ recombination</term> at an early stage of <term sem="Other" id="T25" lex="T_cell_development"><term sem="Cell_natural" id="A6">T cell</term> development</term>.</sentence>
<event id="E7">
<type class="Regulation" />
<theme idref="T17" />
<cause idref="T19" />
<clue>We propose that BEAD-1 functions as a boundary that separates the TCR alpha/delta locus into distinct regulatory domains <clueType>controlled</clueType> <linkCause>by</linkCause> Edelta and the TCR alpha enhancer, and that it prevents Edelta from opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell development.</clue>
</event>
<event id="E8">
<type class="Regulation" />
<theme idref="T17" />
<cause idref="T20" />
<clue>We propose that BEAD-1 functions as a boundary that separates the TCR alpha/delta locus into distinct regulatory domains <clueType>controlled</clueType> <linkCause>by</linkCause> Edelta and the TCR alpha enhancer, and that it prevents Edelta from opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell development.</clue>
</event>
<event id="E9">
<type class="Regulation" />
<theme idref="E7" />
<cause idref="T16" />
<clue>We propose that BEAD-1 functions as a boundary that <clueType>separates</clueType> the TCR alpha/delta locus <clueType>into distinct regulatory domains</clueType> controlled by Edelta and the TCR alpha enhancer, and that it prevents Edelta from opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell development.</clue>
</event>
<event id="E10">
<type class="Regulation" />
<theme idref="E8" />
<cause idref="T16" />
<clue>We propose that BEAD-1 functions as a boundary that <clueType>separates</clueType> the TCR alpha/delta locus <clueType>into distinct regulatory domains</clueType> controlled by Edelta and the TCR alpha enhancer, and that it prevents Edelta from opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell development.</clue>
</event>
<event id="E11">
<type class="DNA_recombination" />
<theme idref="T23" />
<clue>We propose that BEAD-1 functions as a boundary that separates the TCR alpha/delta locus into distinct regulatory domains controlled by Edelta and the TCR alpha enhancer, and that it prevents Edelta from <clueType>opening the chromatin</clueType> <linkTheme>of</linkTheme> the TCR alpha joining gene segments <clueType>for VDJ recombination</clueType> <clueTime>at an early stage of T cell development</clueTime>.</clue>
<comment>NER T23 MOD</comment>
</event>
<event id="E12">
<type class="Positive_regulation" />
<theme idref="E11" />
<cause idref="T21" />
<clue>We propose that BEAD-1 functions as a boundary that separates the TCR alpha/delta locus into distinct regulatory domains controlled by Edelta and the TCR alpha enhancer, and that it prevents Edelta <linkTheme>from</linkTheme> opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell development.</clue>
<comment>NO CLUETYPE</comment>
</event>
<event id="E13">
<type class="Negative_regulation" />
<theme idref="E12" />
<cause idref="T16" />
<clue>We propose that BEAD-1 functions as a boundary that separates the TCR alpha/delta locus into distinct regulatory domains controlled by Edelta and the TCR alpha enhancer, and that <corefCause>it</corefCause> <clueType>prevents</clueType> Edelta from opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell development.</clue>
</event>
<event id="E14">
<type class="Cell_differentiation" />
<theme idref="A6" />
<clue>We propose that BEAD-1 functions as a boundary that separates the TCR alpha/delta locus into distinct regulatory domains controlled by Edelta and the TCR alpha enhancer, and that it prevents Edelta from opening the chromatin of the TCR alpha joining gene segments for VDJ recombination at an early stage of T cell <clueType>development</clueType>.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== Beira-BF/genia-event/original-data/GENIAcorpus_event/8725939.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GENIA//DTD GENIA ANNOTATION EVENT 2.0//EN" "../GENIAtypes/GENIA_event_20.dtd">
<Annotation created="07/01/07" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=8725939" creator="Yumiko Katsu">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8725939</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Regulation of <term sem="Other" id="T1" lex="gene_expression">gene expression</term> at early stages of <cons sem="(AND Other Other)" id="T2" lex="(AND B-cell_differentiation T-cell_differentiation)"><frag id="F1"><term sem="Cell_natural" id="A1">B-cell</term></frag> and <frag id="F2"><term sem="Cell_natural" id="A2">T-cell</term></frag> <frag id="F3">differentiation</frag></cons>.</sentence>
<event id="E1">
<type class="Regulation" />
<theme idref="T1" />
<clue><clueType>Regulation</clueType> <linkTheme>of</linkTheme> gene expression <clueTime>at early stages of B-cell and T-cell differentiation</clueTime>.</clue>
</event>
<event id="E2">
<type class="Cell_differentiation" />
<theme idref="A1" />
<clue>Regulation of gene expression at early stages of B-cell and T-cell <clueType>differentiation</clueType>.</clue>
</event>
<event id="E3">
<type class="Cell_differentiation" />
<theme idref="A2" />
<clue>Regulation of gene expression at early stages of B-cell and T-cell <clueType>differentiation</clueType>.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S2">The expression of distinct sets of <term sem="DNA_domain_or_region" id="A3">genes</term> at different stages of <cons sem="(AND Other Other)" id="T3" lex="(AND B-lymphocyte_differentiation T-lymphocyte_differentiation)"><frag id="F4"><term sem="Cell_natural" id="A4">B-lymphocyte</term></frag> and <frag id="F5"><term sem="Cell_natural" id="A5">T-lymphocyte</term></frag> <frag id="F6">differentiation</frag></cons> is controlled at the level of transcription.</sentence>
<event id="E4">
<type class="Gene_expression" />
<theme idref="A3" />
<clue>The <clueType>expression</clueType> <linkTheme>of</linkTheme> distinct sets of genes <clueTime>at different stages of B-lymphocyte and T-lymphocyte differentiation</clueTime> is controlled at the level of transcription.</clue>
</event>
<event id="E5">
<type class="Cell_differentiation" />
<theme idref="A4" />
<clue>The expression of distinct sets of genes at different stages of B-lymphocyte and T-lymphocyte <clueType>differentiation</clueType> is controlled at the level of transcription.</clue>
</event>
<event id="E6">
<type class="Cell_differentiation" />
<theme idref="A5" />
<clue>The expression of distinct sets of genes at different stages of B-lymphocyte and T-lymphocyte <clueType>differentiation</clueType> is controlled at the level of transcription.</clue>
</event>
<event id="E7">
<type class="Regulation" />
<theme idref="E4" />
<cause idref="E9" />
<clue>The expression of distinct sets of genes at different stages of B-lymphocyte and T-lymphocyte differentiation is <clueType>controlled</clueType> <linkCause>at</linkCause> the level of transcription.</clue>
</event>
<event id="E8">
<type class="Transcription" />
<theme idref="A3" />
<clue>The expression of distinct sets of genes at different stages of B-lymphocyte and T-lymphocyte differentiation is controlled at the level of <clueType>transcription</clueType>.</clue>
</event>
<event id="E9">
<type class="Regulation" />
<theme idref="E8" />
<clue>The expression of distinct sets of genes at different stages of B-lymphocyte and T-lymphocyte differentiation is controlled at the <clueType>level</clueType> <linkTheme>of</linkTheme> transcription.</clue>
</event>
<sentence id="S3">A number of recent studies have described interactions between <term sem="Protein_family_or_group" id="T4" lex="transcription_factor">transcription factors</term> in <term sem="Tissue_natural" id="T5" lex="lymphocyte">lymphocytes</term> that provide new insights into <term sem="Other" id="A6">mechanisms</term> regulating <term sem="Other" id="T6" lex="gene_expression">gene expression</term>.</sentence>
<event id="E10">
<type class="Correlation" />
<theme idref="T4" />
<clue>A number of recent studies have described <clueType>interactions</clueType> <linkTheme>between</linkTheme> transcription factors <clueLoc>in lymphocytes</clueLoc> that provide new insights into mechanisms regulating gene expression.</clue>
</event>
<event id="E11">
<type class="Regulation" />
<theme idref="T6" />
<cause idref="A6" />
<clue>A number of recent studies have described interactions between transcription factors in lymphocytes that provide new insights into mechanisms <clueType>regulating</clueType> gene expression.</clue>
</event>
<sentence id="S4">These mechanisms include the assembly of <term sem="Protein_complex" id="T7" lex="higher_order_nucleoprotein_complex">higher order nucleoprotein complexes</term> and other <term sem="Other" id="T8" lex="protein-protein_interaction"><term sem="Protein_molecule" id="A7">protein</term>-<term sem="Protein_molecule" id="A8">protein</term> interactions</term> that enhance the <term sem="Other" id="A9">functional specificity of <term sem="Protein_family_or_group" id="T9" lex="transcriptional_regulator">transcriptional regulators</term></term> in <term sem="Tissue_natural" id="T10" lex="lymphocyte">lymphocytes</term>.</sentence>
<event id="E12">
<type class="Protein_metabolism" />
<theme idref="T7" />
<clue>These mechanisms include the <clueType>assembly</clueType> <linkTheme>of</linkTheme> higher order nucleoprotein complexes and other protein-protein interactions that enhance the functional specificity of transcriptional regulators in lymphocytes.</clue>
</event>
<event id="E17">
<type class="Binding" />
<theme idref="A7" />
<theme idref="A8" />
<clue>These mechanisms include the assembly of higher order nucleoprotein complexes and other protein-protein <clueType>interactions</clueType> that enhance the functional specificity of transcriptional regulators in lymphocytes.</clue>
</event>
<event id="E18">
<type class="Positive_regulation" />
<theme idref="A9" />
<cause idref="E17" />
<clue>These mechanisms include the assembly of higher order nucleoprotein complexes and other protein-protein interactions that <clueType>enhance</clueType> the functional specificity of transcriptional regulators <clueLoc>in lymphocytes</clueLoc>.</clue>
<comment>TPS A9</comment>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
